version: '3.8'

services:
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: php:5.6.4
#    ports:
#      - "8080:80"
#    volumes:
#      - ./:/var/www/html
##      - ./php.ini:/etc/php/5.6/cli/php.ini
#    depends_on:
#      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
